apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: databasevolume
  labels:
    name: databasevolume
spec:
  storageClassName: databasevolume
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: databasevolume
  labels:
    name: databasevolume
spec:
  storageClassName: databasevolume
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/dbvol"